dist: trusty

addons:
  apt:
    packages:
      - openjdk-6-jdk

install:
  - .travis/pre-install.sh

language: java
jdk:
  - oraclejdk8

script:
  - mvn test javadoc:javadoc

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.embedmysql
    - $HOME/.embedpostgresql
    - $HOME/.m2
